# Generated by Django 5.0.7 on 2025-05-11 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cams', '0004_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
