# Generated by Django 5.0.7 on 2025-05-12 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cams', '0006_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
