# Generated by Django 5.0.7 on 2025-05-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cams', '0007_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='Img/')),
            ],
        ),
    ]
