# Generated by Django 5.0.7 on 2025-05-13 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cams', '0008_serviceprovider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceProvider',
        ),
    ]
