# Generated by Django 5.0.7 on 2025-05-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cams', '0009_delete_serviceprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
