# Generated by Django 5.0.7 on 2025-05-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cams', '0011_service_yourmodel_booking_customuser_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='reset_token',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='token_expiry',
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
