# Generated by Django 5.0.7 on 2025-05-18 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cams', '0012_remove_customer_reset_token_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
